#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
name: Build OpenWrt Package

on:
  workflow_dispatch:
    inputs:
      Arch:
        description: 目标架构
        default: x86-64
      Version:
        description: 版本号
        type: choice
        default: '22.03.2'
        options:
          - '22.03.3'
          - '22.03.2'
          - '21.02.5'
      Package:
        description: 软件包
        default: luci-app-vlmcsd

env:
  ARCH: ${{ inputs.Arch }}
  VERSION: ${{ inputs.Version }}
  SDK_URL: https://downloads.openwrt.org/releases/
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 下载 SDK
      working-directory: /workdir
      run: |
        df -hT $PWD
        case $VERSION in
        '22.03.2' | '22.03.3')
          GCC_VERSION='11.2.0';;
        '21.02.5')
          GCC_VERSION='8.4.0';;
        *)
          echo 出现错误: 版本号 $VERSION 无效;;
        esac
        URL="${SDK_URL}${VERSION}/targets/${ARCH/-//}/openwrt-sdk-${VERSION}-${ARCH}_gcc-${GCC_VERSION}_musl.Linux-x86_64.tar.xz"
        echo 将下载 $URL
        curl -fL -m 60 -o sdk.tar.xz $URL
        tar -xf sdk.tar.xz -C /workdir
        ls -l 
        mv openwrt-sdk* openwrt

    - name: 载入自定义源文件和自定义脚本1
      run: |
        ls -l
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd /workdir/openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: 更新 feeds
      working-directory: /workdir/openwrt
      run: ./scripts/feeds update -a

    - name: 安装 feeds
      working-directory: /workdir/openwrt
      run: ./scripts/feeds install -a

    - name: 载入配置文件
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE /workdir/openwrt/.config
        chmod +x $DIY_P2_SH
        cd /workdir/openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: 预下载包
      id: package
      working-directory: /workdir/openwrt
      run: |
        make defconfig
        make download -j8 ${{ github.event.inputs.Package }}
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 缓存 dl 目录
      uses: actions/cache@v2
      with:
        path: /workdir/openwrt/dl
        key: ${{ runner.os }}-dl-${{ hashFiles('**/feeds.conf.default') }}
        restore-keys: |
          ${{ runner.os }}-dl-

    - name: 编译软件包
      working-directory: /workdir/openwrt
      id: compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) package/${{ github.event.inputs.Package }}/compile || make -j1 package/${{ github.event.inputs.Package }}/compile || make -j1 V=s package/${{ github.event.inputs.Package }}/compile
        echo "::set-output name=status::success"
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 检查空间使用
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.FILE_DATE }}
        path: /workdir/openwrt/bin

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

